Add mathify script for converting math to svg
The mathify script uses "neb mathify" to convert math in HTML into svg
(by default, which can be changed by specifying `MATH_FORMAT`).

"neb mathify" uses docker, that currently does not work inside a docker
container.  People don't recommend running docker inside docker, the way
to do this is by running a sibling container.  You would mount your
host's `/var/run/docker.sock` in your container and launch a new
container in your container from your host.  The complication comes from
the path being incorrect.  When I tried this, I got this error:

```
docker.errors.APIError: 400 Client Error: Bad Request ("invalid mount
config for type "bind": bind source path does not exist:
/code/data/intro-business")
```

I think this is because `/code/data/intro-business` does not exist on
the host.

Due to this complication, I decided to restrict the mathify script to
work only locally.  To not mess with someone with a python virtualenv
set up to work in a container, the script creates a new virtualenv in
`venv.local`.