Inipit.iago (#1066)
* added Precalculus to books.txt

* updated manifest.json with Precalculus entry

* created recipe for precalculus

* created styleguide

* removed broken code

* fixing styleguides

* changed numbering of try it notes

* changed the numbering of figures and tables

* fixing answer key

* fixing exercises numbering

* compiled css

* Section separated links for titles in eoc  (#837)

* Section separated links for titles in eoc issue #715

* EOC & Answer Key composite chapters (#845)

* composite chapter EOB and EOC
* gitignore  (ignore data/ and resources/

* changing answer key to composite page

* compiled recipes

* Feature flag -> Release flag

* Rebuild release flag chart

* added Calculus to books.txt

* updated manifest.json with Calculus entry

* add calculus vol2 and vol3 to books.txt

* created recipe for calculus

* created styleguide

* fix styleguide

* change note name (#875)

* Remove numbering-continuously flag

* Remove completed release flags

* change answer key to composite page

* change _feature to _release in book.scss

* compiled css

* fixed styleguide

* fixed commentary in styleguide

* fixed try it whitespaces

* changed display of section exercises

* fixed styleguide

* numbering of equations

* compile css

* fixed numering of the figures

* numbered list in abstract

* added a feature-flag

* Update _feature.scss

removed unnecessary empty line

* added reset at module to try it notes in precalc books (#934)

* added reset at module to try it notes in precalc books

* fixed numbering of examples inside sections (#928)

* fixed numbering of examples inside sections

* changed numbering of figures within modules

* delete abstractList and change lists mixins

* compile calculus css

* compile other books css

* compile css

* release flag for titles in examples

* compile css

* trash selected element config

* compile css

* remove impact on tables

* compile css

* change title in problem

* fixed section exercises numbering, added  option

* apply requested changes

* changes only for examples

* separate selectors

* compile calculus css

* compile other books css

* changed table numbering within sections

* removed unnecessary heading

* added section headers to key concepts

* added learning objective heading

* copy title to labelText variable

* fixed EOC exercise numbering to be reseted at composite page

* bolded titles in examples

* reduce code

* added output css

* add selector and name keys

* added chapter outline

* fixed figure numbering in EoC

* changed the numbering of links to examples

* create release flag

* apply new keys to dev-math and chemistry

* remove flag from config file

* moved precalculus entry in release flag to new line

* moved the composite-page reset selector from mixin to be passed in the generator

* Add katalyst01.cnx.org as a fetch-html host

When trying to fetch a book from katalyst01
`HOST=katalyst01.cnx.org ./script/fetch-html calculus-vol1`:

```
Error: unknown environment: 'katalyst01.cnx.org'
./script/fetch-html: ERROR: could not run [neb get -d ./data/calculus-vol1/raw katalyst01.cnx.org col11964 ]
```

The reason is because neb doesn't know about "katalyst01.cnx.org".

Add katalyst01.cnx.org to neb config so neb get can fetch from
katalyst01.cnx.org.

* fixed tables numbering and links' to tables numbering

* add calculus collection number

* reworked links to examples numbering

* Team Flow (#840)

* trash selected element mixin

* apply mixin for anatomy

* apply mixin for u-physics

* notes in answer key separated by sections

* changed the tryit solutions container class

* small fix for the try it title

* check impact of some parts of code

* added release flag

* add modify subtitle id mixin

* generated release chart

* fixed indentation and changed the class to be reusable in the future

* add reference mixin

* change TrashSelectedElements config to map

* include reference mixin in other pass

* change TrashSelectedElements config to simple list

* removed release flag and applied unnumbered element change only to precalculus

* updated readme file

* updated common-stuff

* updated books configs to use unnumbered elements

* changed unnumbered exercises and equations to unnumbered elements in generator

* compiled css and some small changes in generator

* create config for subtitle labels

* remove changes from setTargetLabels mixin

* style header and solution header

* add indent

* add section titles to Summaries

* apply changes for trash elements

* issue-1012 add glossary handling

* apply changes from inipit.iago for calculus